# Generated by Django 2.1.5 on 2019-02-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_label', models.CharField(max_length=400, verbose_name='star label')),
                ('star_time', models.DateTimeField(verbose_name='star born')),
                ('xCoord', models.CharField(max_length=12, verbose_name='x')),
                ('yCoord', models.CharField(max_length=12, verbose_name='y')),
            ],
        ),
    ]
