# Generated by Django 2.1.5 on 2019-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starrynight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='star_message',
            field=models.CharField(default='lol', max_length=512, verbose_name='star message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='star_label',
            field=models.CharField(max_length=30, verbose_name='star label'),
        ),
    ]
